apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bienit/flask-demo.git
    targetRevision: master
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
